name: JodellePowerMining
main: jodelle.powermining.PowerMining
version: 1.1.1
authors: [JodelleLover, Holt]
description: Implements Hammer, Excavator and Plow tools for faster mining, version updated from BloodyShade.
api-version: "1.21.4"
softdepend: [worldguard, Jobs]

commands:
    powermining:
        usage: /<command>
        description: Gives a powertool
        aliases: [jpm]

permissions:
    powermining.all:
        description: Grants all permissions
        default: op
        children:
            powermining.admin: true
            powermining.version: true
            powermining.give: true
            powermining.highdurability: true
            powermining.craft.all: true
            powermining.use.all: true
            powermining.enchant.all: true

    powermining.highdurability:
        description: Allows player's PowerTool to use only 1 durability per use
        default: true

    powermining.version:
        description: Allows using `/powermining version`
        default: op
    
    powermining.give:
        description: Allows player to receive a Powertool of his choice
        default: op

    powermining.admin:
        description: Grants access to all admin commands
        default: op
        children:
            powermining.admin.reload: true
            powermining.admin.language: true
            powermining.admin.debug: true
            powermining.admin.help: true

    powermining.admin.reload:
        description: Allows using `/powermining admin reload`
        default: op

    powermining.admin.language:
        description: Allows using `/powermining admin language <language>`
        default: op

    powermining.admin.debug:
        description: Allows using `/powermining admin debug`
        default: op

    powermining.admin.help:
        description: Allows using `/powermining admin help`
        default: op

    powermining.craft.all:
        description: Allows players to craft all PowerTools
        default: op
        children:
            powermining.craft.hammer.all: true
            powermining.craft.excavator.all: true
            powermining.craft.plow.all: true

    powermining.craft.hammer.all:
        description: Allows players to craft all hammers
        default: op
        children:
            powermining.craft.hammer.wooden: true
            powermining.craft.hammer.stone: true
            powermining.craft.hammer.iron: true
            powermining.craft.hammer.golden: true
            powermining.craft.hammer.diamond: true
            powermining.craft.hammer.netherite: true

    powermining.craft.hammer.wooden:
        description: Allows players to craft the Wooden Hammer
        default: false
    powermining.craft.hammer.stone:
        description: Allows players to craft the Stone Hammer
        default: false
    powermining.craft.hammer.iron:
        description: Allows players to craft the Iron Hammer
        default: false
    powermining.craft.hammer.golden:
        description: Allows players to craft the Golden Hammer
        default: false
    powermining.craft.hammer.diamond:
        description: Allows players to craft the Diamond Hammer
        default: false
    powermining.craft.hammer.netherite:
        description: Allows players to craft the Netherite Hammer
        default: false

    powermining.craft.plow.all:
        description: Allows players to craft all Plows
        default: op
        children:
            powermining.craft.plow.wooden: true
            powermining.craft.plow.stone: true
            powermining.craft.plow.iron: true
            powermining.craft.plow.golden: true
            powermining.craft.plow.diamond: true
            powermining.craft.plow.netherite: true

    powermining.craft.plow.wooden:
        description: Allows players to craft the Wooden Plow
        default: false
    powermining.craft.plow.stone:
        description: Allows players to craft the Stone Plow
        default: false
    powermining.craft.plow.iron:
        description: Allows players to craft the Iron Plow
        default: false
    powermining.craft.plow.golden:
        description: Allows players to craft the Golden Plow
        default: false
    powermining.craft.plow.diamond:
        description: Allows players to craft the Diamond Plow
        default: false
    powermining.craft.plow.netherite:
        description: Allows players to craft the Netherite Plow
        default: false

    powermining.craft.excavator.all:
        description: Allows players to craft all Excavators
        default: op
        children:
            powermining.craft.excavator.wooden: true
            powermining.craft.excavator.stone: true
            powermining.craft.excavator.iron: true
            powermining.craft.excavator.golden: true
            powermining.craft.excavator.diamond: true
            powermining.craft.excavator.netherite: true

    powermining.craft.excavator.wooden:
        description: Allows players to craft the Wooden Excavator
        default: false
    powermining.craft.excavator.stone:
        description: Allows players to craft the Stone Excavator
        default: false
    powermining.craft.excavator.iron:
        description: Allows players to craft the Iron Excavator
        default: false
    powermining.craft.excavator.golden:
        description: Allows players to craft the Golden Excavator
        default: false
    powermining.craft.excavator.diamond:
        description: Allows players to craft the Diamond Excavator
        default: false
    powermining.craft.excavator.netherite:
        description: Allows players to craft the Netherite Excavator
        default: false

    powermining.use.all:
        description: Allows players to use all Hammers and Excavators
        default: op
        children:
            powermining.use.hammer.all: true
            powermining.use.excavator.all: true
            powermining.use.plow.all: true
            powermining.use.commands: true

    powermining.use.commands:
        description: Allows players to use default commands
        default: op
        
    powermining.use.hammer.all:
        description: Allows players to use all hammers
        default: op
        children:
            powermining.use.hammer.wooden: true
            powermining.use.hammer.stone: true
            powermining.use.hammer.iron: true
            powermining.use.hammer.golden: true
            powermining.use.hammer.diamond: true
            powermining.use.hammer.netherite: true

    powermining.use.hammer.wooden:
        description: Allows players to use the Wooden Hammer
        default: false
    powermining.use.hammer.stone:
        description: Allows players to use the Stone Hammer
        default: false
    powermining.use.hammer.iron:
        description: Allows players to use the Iron Hammer
        default: false
    powermining.use.hammer.golden:
        description: Allows players to use the Golden Hammer
        default: false
    powermining.use.hammer.diamond:
        description: Allows players to use the Diamond Hammer
        default: false
    powermining.use.hammer.netherite:
        description: Allows players to use the Netherite Hammer
        default: false

    powermining.use.plow.all:
        description: Allows players to use all Plows
        default: op
        children:
            powermining.use.plow.wooden: true
            powermining.use.plow.stone: true
            powermining.use.plow.iron: true
            powermining.use.plow.golden: true
            powermining.use.plow.diamond: true
            powermining.use.plow.netherite: true

    powermining.use.plow.wooden:
        description: Allows players to use the Wooden Plow
        default: false
    powermining.use.plow.stone:
        description: Allows players to use the Stone Plow
        default: false
    powermining.use.plow.iron:
        description: Allows players to use the Iron Plow
        default: false
    powermining.use.plow.golden:
        description: Allows players to use the Golden Plow
        default: false
    powermining.use.plow.diamond:
        description: Allows players to use the Diamond Plow
        default: false
    powermining.use.plow.netherite:
        description: Allows players to use the Netherite Plow
        default: false

    powermining.use.excavator.all:
        description: Allows players to use all excavators
        default: op
        children:
            powermining.use.excavator.wooden: true
            powermining.use.excavator.stone: true
            powermining.use.excavator.iron: true
            powermining.use.excavator.golden: true
            powermining.use.excavator.diamond: true
            powermining.use.excavator.netherite: true

    powermining.use.excavator.wooden:
        description: Allows players to use the Wooden Excavator
        default: false
    powermining.use.excavator.stone:
        description: Allows players to use the Stone Excavator
        default: false
    powermining.use.excavator.iron:
        description: Allows players to use the Iron Excavator
        default: false
    powermining.use.excavator.golden:
        description: Allows players to use the Golden Excavator
        default: false
    powermining.use.excavator.diamond:
        description: Allows players to use the Diamond Excavator
        default: false
    powermining.use.excavator.netherite:
        description: Allows players to use the Netherite Excavator
        default: false

    powermining.enchant.all:
        description: Allows players to enchant all Hammers and Excavators
        default: op
        children:
            powermining.enchant.hammer.all: true
            powermining.enchant.excavator.all: true
            powermining.enchant.plow.all: true

    powermining.enchant.hammer.all:
        description: Allows players to enchant all hammers
        default: op
        children:
            powermining.enchant.hammer.wooden: true
            powermining.enchant.hammer.stone: true
            powermining.enchant.hammer.iron: true
            powermining.enchant.hammer.golden: true
            powermining.enchant.hammer.diamond: true
            powermining.enchant.hammer.netherite: true

    powermining.enchant.hammer.wooden:
        description: Allows players to enchant the Wooden Hammer
        default: false
    powermining.enchant.hammer.stone:
        description: Allows players to enchant the Stone Hammer
        default: false
    powermining.enchant.hammer.iron:
        description: Allows players to enchant the Iron Hammer
        default: false
    powermining.enchant.hammer.golden:
        description: Allows players to enchant the Golden Hammer
        default: false
    powermining.enchant.hammer.diamond:
        description: Allows players to enchant the Diamond Hammer
        default: false
    powermining.enchant.hammer.netherite:
        description: Allows players to enchant the Netherite Hammer
        default: false

    powermining.enchant.plow.all:
        description: Allows players to enchant all Plows
        default: op
        children:
            powermining.enchant.plow.wooden: true
            powermining.enchant.plow.stone: true
            powermining.enchant.plow.iron: true
            powermining.enchant.plow.golden: true
            powermining.enchant.plow.diamond: true
            powermining.enchant.plow.netherite: true

    powermining.enchant.plow.wooden:
            description: Allows players to enchant the Wooden Plow
            default: false
    powermining.enchant.plow.stone:
            description: Allows players to enchant the Stone Plow
            default: false
    powermining.enchant.plow.iron:
            description: Allows players to enchant the Iron Plow
            default: false
    powermining.enchant.plow.golden:
            description: Allows players to enchant the Golden Plow
            default: false
    powermining.enchant.plow.diamond:
            description: Allows players to enchant the Diamond Plow
            default: false
    powermining.enchant.plow.netherite:
            description: Allows players to enchant the Netherite Plow
            default: false

    powermining.enchant.excavator.all:
        description: Allows players to enchant all excavators
        default: op
        children:
            powermining.enchant.excavator.wooden: true
            powermining.enchant.excavator.stone: true
            powermining.enchant.excavator.iron: true
            powermining.enchant.excavator.golden: true
            powermining.enchant.excavator.diamond: true
            powermining.enchant.excavator.netherite: true

    powermining.enchant.excavator.wooden:
        description: Allows players to enchant the Wooden Excavator
        default: false
    powermining.enchant.excavator.stone:
        description: Allows players to enchant the Stone Excavator
        default: false
    powermining.enchant.excavator.iron:
        description: Allows players to enchant the Iron Excavator
        default: false
    powermining.enchant.excavator.golden:
        description: Allows players to enchant the Golden Excavator
        default: false
    powermining.enchant.excavator.diamond:
        description: Allows players to enchant the Diamond Excavator
        default: false
    powermining.enchant.excavator.netherite:
        description: Allows players to enchant the Netherite Excavator
        default: false