name: Build Plugin

on:
  push:
    branches:
      - master

jobs:
  build_plugin_prod:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.9-eclipse-temurin-21-jammy
      options: -e MAVEN_OPTS=-Dmaven.repo.local=.m2/repository

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Maven Repository Directory
        run: mkdir -p .m2/repository

      - name: Build with Maven
        run: mvn clean package

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}-${{ github.ref_name }}-${{ github.run_id }}
          path: target/JodellePowerMining*.jar
